server:
  port: 3001

spring:
  datasource:
    # Configuración de la Base de Datos (Túnel SSH puerto 3307)
    url: jdbc:mysql://127.0.0.1:3307/grupo5_db?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: bd_grupo5
    password: Grupo05_bd
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect

  # --- CONFIGURACIÓN DE CORREO GMAIL ---
  mail:
    host: smtp.gmail.com
    port: 587
    username: kokystiendas@gmail.com
    password: ftlv jloe jdwv kium
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  # Deshabilitar H2
  h2:
    console:
      enabled: false

logging:
  level:
    root: INFO
    com.koky.web: DEBUG
    org.hibernate.SQL: DEBUG

# ----- CONFIGURACIONES DE LA APP -----
app:
  # URL pública para los correos (IP del Servidor)
  frontend:
    url: http://72.61.9.249:3001

  # Configuración JWT
  jwt:
    secret: ClaveSecretaSuperSeguraParaKokyTiendaVirtual2025
    expirationMinutes: 120